-- To query the number of pieces of equipment used 
-- in each of the projects
SELECT P.NAME PROJECT_NAME,
	COUNT(EL.EQUIP_ID) NUM_OF_EQUIPMENT
FROM PROJECT P
JOIN PROJECT_LOC PL ON P.PROJECT_ID = PL.PROJECT_ID
JOIN EQUIP_LOC EL ON PL.LOC_ID = EL.LOC_ID
GROUP BY PROJECT_NAME;