-- To query the number of pieces of equipment 
-- at each of the monitoring locations
SELECT L.NAME LOCATION,
	COUNT(E.EQUIP_ID) NUMBER_OF_EQUIPMENT
FROM EQUIPMENT E
JOIN EQUIP_LOC EL ON E.EQUIP_ID = EL.EQUIP_ID
JOIN LOC L ON EL.LOC_ID = L.LOC_ID
GROUP BY LOCATION
ORDER BY NUMBER_OF_EQUIPMENT DESC;